### ISSUE TITLE
Not working, also pytub can't get required

### ISSUE THREAD

**Issue by Tomato6966** [xXFireSlimeXx/youtube_downloader#1]
![image](https://user-images.githubusercontent.com/68145571/124131817-721b6880-da80-11eb-9783-830c018f2a0b.png)

![image](https://user-images.githubusercontent.com/68145571/124131884-87909280-da80-11eb-83ed-2b0c7325ca74.png)

**Comment by xXFireSlimeXx** [comment]
Please send a Screenshot from your code

**Comment by xXFireSlimeXx** [comment]
You mean, that you can't install PyTube or what?

**Comment by xXFireSlimeXx** [comment]
Please Update your Python to Version 3.6< and use the command python3 get-pip.py to install pip after this you can use pip3 install pytube

**Comment by Tomato6966** [comment]
thx
